language: java
jdk:
- openjdk8
script: mvn clean verify

deploy:
  provider: heroku
  api_key:
    secure: NDBKyBKnSaldSSkmDkvRpQ8swdP+iOThDrtSgoOsdZNmyAi+t+aubyjWEWOqkHYHRP6iz+x0MuxYlhc/LzSxAgMyDUmZ7ppaAhVl5+EPL8y5e0F2GOCpgqs1A8N5ky6R7ccJtRmPkgU+re06P/GvgNTyUHERiv/hho1Td6XACGj7x5T4N+zz0TNk8TdRGfHHa7XtauZUmcKSFB5UsVuxtmggzVKULo8o1wmqp8tFZIUVbLR0U09OAuBS93POhIZCxQ5Neo0DWzaaXpZV9JCtV3oBVosZ1ooZIsds/LMAqXE37qyTzf8XahfrWMzwsNzKrADXTpXX7MzwW9d3C7UcaCcx4FOScz4ErG0peosVo8tASuzWJMVG2VJk+9n0PmR/tnQDYUIowW5ysoXsogQO1lBTE54rbHO6iW7/y6yeuB+JU6ELOHj6OGnwAShfLo8fk4d8ZzuzfNk6nn+UsS5EX1+TqS5bsaGvri4rCgXTy+NSAoBEvpzQymcYuW+v8yhyj6qHBwonrigRbQPVb5V19FDHCtgjjbs9DBEsZ8X9Is0u1YOsSx3bvAisIQlNxHWnbfIGah+fPc7OL5TMl3tg0FU9OWPVQ8hXX6UwuYccwF8EkdkPJ2jUC6gEN0gjpqPJVBxmQbtT7OqXh1Qlb4Exe2YKAkzkJZ5Xf/qL93y21tE=
  app: balcony-fall
