language: java
jdk:
- openjdk8
script: mvn clean verify

deploy:
  provider: heroku
  api_key:
    secure: oGCa2zpGYyS31we+f99dnONSdNe0S58rdiSDuFHN6NlwoSscvaEeV0HyVXx0D312njnjVPUOonwdtGElc6Rd34gwkGC9DxVjmP8T8OeHymcRXYwBqeWGb3Um0bCWT6HH1Dj3ZcBeC4yJiVXJhWQSb/ehLf/knSIp7Px3qB53YByakKAptZtUylhobJa+6Z3Y67UtYRRYtokRXm6znA/xDF4Z0dtGEHlaPdng8wKU4yd/oIdJwe6zMOBZkcrFe4GvfnNZT+5vXRM1ptgBvCx1HiAJOYvheHAaMzVoPoY4PQxl2QY7uKRJGTMTTY9Wnh9VPiGe+m8ZjxdlZWto/Cu7iFIgvJI89u4jJpAaq5lWjv/+gSL0+M5cnAzE7WTp3vKrQqLlzhIi9lcBHOnnMjbcXZF2Qf5B3fcGZFbWH82qhhY5H+kuenkzLUCjsoXcsgXXydjMs0OMiSNYqJpS0sCvXYh2gYePKbHJNwT9aQc6xSY0Oophr8Q9aoQoH5muin6NQHs8r+qpeJPJSFSyQW2KexVC3Mho8AlgOxKpQirZHfBtHZ4Q07ZFcpIbSl0412WtI5GKSd4qH4zbFfiPNc0mPhuoYsHSY4Qn5CSr3+jZxwOVCRHtHncpwKYQOB0cSHZNIN3xgICBMhlI3mSmCg23xoAUjDDw3TgyjTNhrM7q4kY=
  app: balcony-fall
