language: java
jdk:
- openjdk8
script: mvn clean verify

deploy:
  provider: heroku
  api_key:
    secure: lPfIx5uX9AY7/QdBEfYbuurO6i3GHxm37STx2tmnjzPzjnTl0RrkT/qyoneLj8m6wYGLXsM5gvfLzl4w1WM7BBFybBhbmtbwvbncZQPaJ48oC41UdXwdDa05OJHtTdcSqlGIx7XwdMWqQY+7rNlJhxNrhghUqjy+G+mcm9YzBHODDgO5N3VSeuBXHjRurJj2bgoewaP1YEhe2Tcrr2jZ5ybzN14HrUiQFhBa+8h8R15DfMrZWwpIcdTBwi85m76pHa2FvXuAsiZPu87EOsX0TSxT3JZ6nq8OVS6KlRSDrn7Nb3D6K/TurOatU+MWKfKEdeSWxA9dSSi1p/Kgw1GKSRZmyO6S19k3z21oxVckshhCsjq1MWjkH/EKUMTbCA5j2xvOO8gJDZwA88/JrrOSPuT1RplyBnE8QA2KeUQYcC4O5y5VP44xxh4AvtoMqiNcC2YWl3atvDXrNrvAlVn/SvSRPG1Dseo4GFzS0Gi26FW9DbRGxzPPXLJk71UFv+oKCef6v+HqUG4coWOKWVdky8FPXp4jGgeExe9fzbJH3m+nbZgxIqHqVTALE/HA36sRr7mBlsiV+L90auuwmARuE4y99+hz/L+KyjRkrklbQS9EReQo6qXgfv5brntbOQeLlgGTG6M3ILbonAv4NjxGAQDKv/c0q+5C8qqohDWh99k=
  app: balcony-fall
