language: java
jdk:
- openjdk8
script: mvn clean verify

deploy:
  provider: heroku
  api_key:
    secure: amj/FfWb5G7U9EycnYljVSjHrDbU8FpP4btHBs58XVzXPwZhB4plJKiAF1KdnRFVTt7yNKTltL+qE8t767hoFJny8nfHW4A4mHr9kOZSU9kUTs8a94V5bVSTsUAmmmBf90u+czBVJnVXvogp1rKqEqpFqZiT7SsrPYif+B9QAxU8rtU74OnDJ3B8AjD32O3zgJVnjdBwE59Gvw5bUoqVNWwcFIwk5bCjM21VKdmimmHbzTPFaB1hpFiJgD9QgBbPfUMpHynYhbiSCx0Mjn0bQm/ccMOYvsYhp7/+/duIZrARtKVhoRNE/QWEqHZvGyI4WkYzKpQrz94Re07OyrQVoJ1UdXMzrm49F0NYykq2z3O9QrRsWS+f/rw+FCSgkaLELxJ2FVTdGWGvg7mztrtSIeMmkU1I2T5UCAalX8Fv5UurzjDUiNbTuoOveAJSo5UJF2h/2stAnjmePo5Dp1agcS1jnYcsv2aXm6tJzbFJiukDXT5kQWhuUQkz7wT4HXQDuPXHdWGnTlhZttdVL5rBdQJTg5CtRrbDRYOS2y7HJvMprvQ3h9xAbvVvQZlbTs5V9d7QE6iCMsvw++4twbKU9oyWKAe8GKw5CT3dRjwrX8F0B8Y8irtXMy+jUe4hwXypKhsG9soW+FsLjTFW0O5/TYuqU3VWQI3ejulrZ77hhRw=
  app: balcony-fall
